spring:
  application:
    name: task-time-tracker-service
  datasource:
    url: jdbc:postgresql://localhost:5432/tasktimetracker_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/task-time-tracker
mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8083

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.authorization: TRACE